### ISSUE TITLE
Possible library mismatch on Windows

### ISSUE THREAD

**Issue by alexraj** [yurishkuro/opentracing-go-nethttp-demo#2]
I am trying to run this on Windows. I install GNU32, to get the glider and grep working. The glider install ran fine. However after the installation, when I try to do "go build .", I get bunch of compilation errors, as given below. The indication seems to suggest the APIs have different signature, and I am not sure how to find right version. Btw, the glider got the jaeger-client-go into the vendor directory, and I had to copy it under C:\Users\<userid>\goworkspace\src\github.com\uber, with out it, it complains package jaeger-client-go is not found.

C:\Users\<userid>\goworkspace\src\github.com\uber\jaeger-client-go\thrift-gen\zipkincore\zipkincollect
or.go:77:20: not enough arguments in call to oprot.Flush
        have ()
        want (context.Context)
C:\Users\<userid>\goworkspace\src\github.com\uber\jaeger-client-go\thrift-gen\zipkincore\zipkincollect
or.go:101:15: cannot assign 1 values to 2 variables
C:\Users\<userid>\goworkspace\src\github.com\uber\jaeger-client-go\thrift-gen\zipkincore\zipkincollect
or.go:147:42: cannot use zipkinCollectorProcessorSubmitZipkinBatch literal (type *zipkinCollectorPro
cessorSubmitZipkinBatch) as type thrift.TProcessorFunction in assignment:
        *zipkinCollectorProcessorSubmitZipkinBatch does not implement thrift.TProcessorFunction (wro
ng type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thri
ft.TException)
C:\Users\<userid>\goworkspace\src\github.com\uber\jaeger-client-go\thrift-gen\zipkincore\zipkincollect
or.go:157:27: not enough arguments in call to processor.Process
        have (int32, thrift.TProtocol, thrift.TProtocol)
        want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
C:\Users\<userid>\goworkspace\src\github.com\uber\jaeger-client-go\thrift-gen\zipkincore\zipkincollect
or.go:165:13: not enough arguments in call to oprot.Flush
        have ()
        want (context.Context)
C:\Users\<userid>\goworkspace\src\github.com\uber\jaeger-client-go\thrift-gen\zipkincore\zipkincollect
or.go:182:14: not enough arguments in call to oprot.Flush

**Comment by kingeasternsun** [comment]
ubuntu 16
go version go1.9.2 linux/amd64

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6b3465]

goroutine 1 [running]:
github.com/uber/jaeger-client-go.NewRemoteReporter(0x91bde0, 0xc42007e230, 0xc420051f38, 0x1, 0x1, 0xc42007e230, 0x0)
	/home/wdy/gitlab/src/github.com/uber/jaeger-client-go/reporter.go:190 +0x55
main.main()
	/home/wdy/gitlab/src/github.com/yurishkuro/opentracing-go-nethttp-demo/main.go:44 +0x317
```

**Comment by yangzhenxiong** [comment]
> ubuntu 16
> go version go1.9.2 linux/amd64
> 
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6b3465]
> 
> goroutine 1 [running]:
> github.com/uber/jaeger-client-go.NewRemoteReporter(0x91bde0, 0xc42007e230, 0xc420051f38, 0x1, 0x1, 0xc42007e230, 0x0)
> 	/home/wdy/gitlab/src/github.com/uber/jaeger-client-go/reporter.go:190 +0x55
> main.main()
> 	/home/wdy/gitlab/src/github.com/yurishkuro/opentracing-go-nethttp-demo/main.go:44 +0x317
> ```

main.go:44
try this: jaeger.NewRemoteReporter(transport)
